
- name: prepare directory to store log files
  hosts: all
  strategy: linear
  
  tasks:
    - name: prepare directory to store log files
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - files/vars
        - files/reports/{{inventory_hostname}}
      when: not (item is exists)
      delegate_to: localhost
      tags:
        - always
        
- name: collect magic variables for bigip devices
  hosts: all
  strategy: linear
  
  tasks:
    - name: collect magic variables for bigip devices
      bigip_device_info:
        provider: "{{provider}}"
        gather_subset:
          - virtual-servers
          - client-ssl-profiles
          - ssl-certs
          - ltm-pools
      register: collect_magic_variables
      delegate_to: localhost
      tags:
        - collect_magic_variables
        
    - name: copy magic variables into log files
      template:
        src: templates/vars/collect_magic_variables.j2
        dest: files/vars/{{inventory_hostname}}.mvars
      delegate_to: localhost
      tags:
        - collect_magic_variables

- name: collect static variables for bigip devices
  hosts: all
  strategy: linear

  tasks:
    - name: collect static variables for bigip devices
      bigip_command:
        provider: "{{provider}}"
        chdir: /
        commands: list ltm profile client-ssl recursive
      register: collect_static_variables
      delegate_to: localhost
      tags:
        - collect_static_variables
        
    - name: copy static variables into log files
      template:
        src: templates/vars/collect_static_variables.j2
        dest: files/vars/{{inventory_hostname}}.svars
      delegate_to: localhost
      tags:
        - collect_static_variables

- name: collect master variables for bigip devices
  hosts: all
  strategy: linear

  tasks:
    - name: include magic variables into play
      include_vars:
        file: files/vars/{{inventory_hostname}}.mvars
        name: include_magic_variables
      delegate_to: localhost
      tags:
        - collect_master_variables
        
    - name: include static variables into play
      include_vars:
        file: files/vars/{{inventory_hostname}}.svars
        name: include_static_variables
      delegate_to: localhost
      tags:
        - collect_master_variables
        
    - name: copy master variables into log files
      template:
        src: templates/vars/collect_master_variables.j2
        dest: files/vars/{{inventory_hostname}}.vars
      delegate_to: localhost
      tags:
        - collect_master_variables

- name: prepare apps reports for bigip devices
  hosts: all
  strategy: linear
  
  tasks:
    - name: include master variables into play
      include_vars: 
        file: files/vars/{{inventory_hostname}}.vars
        name: include_master_variables
      delegate_to: localhost
      tags:
        - prepare_apps_reports
        
    - name: prepare apps reports for bigip devices
      template:
        src: templates/reports/prepare_apps_reports.j2
        dest: files/reports/{{inventory_hostname}}/{{inventory_hostname}}_Apps.csv
      delegate_to: localhost
      tags:
        - prepare_apps_reports
        
- name: consolidate apps reports for bigip devices
  hosts: localhost
  strategy: linear
  
  tasks:
    - name: consolidate apps reports for bigip devices
      shell: "{{item}}"
      with_items:
        - echo "LB;Virtual;Virtual Type;Virtual IP;Virtual Port;Virtual Status;Client SSL;SSL Certificate;Certificate Subject;Certificate Issuer;Certificate Expiration;Server SSL;SNAT;Pool;Health Monitor;LB Method;Pool Member;Persist;iRule" > files/reports/{{"%Y%m%d" | strftime}}_Apps.csv
        - cat files/reports/*/*_Apps.csv >> files/reports/{{"%Y%m%d" | strftime}}_Apps.csv
      run_once: yes
      delegate_to: localhost
      tags:
        - consolidate_apps_reports
